---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kbot
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/vvadymv/kbot

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: default
spec:
  chart:
    spec:
      chart: ./helm
      reconcileStrategy: Revision
      version: "v*"
      sourceRef:
        kind: GitRepository
        name: kbot
  interval: 1m0s
