apiVersion: v1
data:
    token: ENC[AES256_GCM,data:eQ+nOPbN6NIynBLm9inp2NispjX9T6LaAyoGYagSx/xGRpTx/STImg9Omf00Du2HDFpGTmcQjrTtcB0TOb633A==,iv:4WbwX2ZewHAOD7b+XJkVAeGoMdxPzAs01C1ZzGsw878=,tag:w4O1Mz4fAal9YFDfUk/cZg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-430300/locations/global/keyRings/kms-key1/cryptoKeys/kms-key1-1
          created_at: "2024-09-08T21:14:40Z"
          enc: CiQALgA0EDaBC79nUQvOrAyR+udRm2CF0uIY4aL7cEaMf0/3tY0SSQDDf90sIU815M3IpchKlUGWbB/OZsVRxB1Ar0+ZDegeQ7g/ngQwx5Ph+nPtrK7tnBhDMiunKNyCF6WCrSQs2iOdxQ14Cttx0n4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-08T21:14:41Z"
    mac: ENC[AES256_GCM,data:+gDR1aYKmXx2NDKx8WWAwfVf9h9CxhTayXJLkWV2EqhiwEVG3WFfQiu5uYImtyrUaiB0DLl8qOtKZPDTxsdzM3F9krU69aW4pLBa9LgwhtHgIMCMLvdfCeB/vnkwrNVOmDR6Aj5vF0IexJYNaGiOWDg8OzjKgHl28hAWiPOP4xg=,iv:4vgBQnwPNgkfgYYwk9POc3gN59YdTWHu/Y+UYIGGnaA=,tag:TxrHCV0hc4k0bqYrDeMv9w==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.9.0
