apiVersion: v1
data:
    token: ENC[AES256_GCM,data:NsprTzlptGhKfcKWnLcNY1siz+pYMwAHGYSzwo8AWsbKOPW+NbdH3B08zWVd0MfoM1w+BvwLqdObP5P5FIHfUw==,iv:6tyP7qhAIKQ4AwgCB6HG+konILGnvnv0rdwrf3SKn9I=,tag:iRZnx+PstwqfX1hwTLZeoQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot
    namespace: test1
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-430300/locations/global/keyRings/kms-key1/cryptoKeys/kms-key1-1
          created_at: "2024-09-08T22:43:39Z"
          enc: CiQALgA0EMMV0tExPymKzNyqHen4gcW3CEIeaPimruscKee9X+ESSADDf90sUPxn2Oje7HP03gJewIhGr/zG8yT5c2NQr/VVxl2oGFJJb2BQvQOgS5LZkDBK7r5RdhADzOujhag032vV5/kbsbpgGQ==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-08T22:43:39Z"
    mac: ENC[AES256_GCM,data:PjSJj7tvSthtZlRelWc0GCiXXyT22BsX3YOCWYYO5EibtewBiZCvpxWvk9JabjK2C5UJjknlZ9H35/BKPOgh1iazvKruciG/0raxVlleldVpT2fic4/veXM1Op+0so/RrvinLlFhqqfrHP5a1J4JgTsI8qcmmPAFYB25NoHbGdc=,iv:PqNngymP2DOPKucbcdGmHwMBrAgI7Qt3QrjxxXXTdFU=,tag:fMRYMhagkV7MlE+U5kLwUQ==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.9.0
